import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY  = os.getenv("OPENAI_API_KEY")
CHAT_MODEL      = "gpt-4o-mini"
EMBEDDING_MODEL = "text-embedding-3-small"
TEMPERATURE     = 0


WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")   

FAISS_K          = 6
BM25_K           = 6
ENSEMBLE_WEIGHTS = [0.4, 0.6]
MAX_SOURCES_SHOW = 5

SEMANTIC_THRESHOLD_TYPE   = "percentile"
SEMANTIC_THRESHOLD_AMOUNT = 90
FALLBACK_CHUNK_SIZE       = 1000
FALLBACK_CHUNK_OVERLAP    = 200

MAX_TOKENS               = 1000
MAX_REQUESTS_PER_SESSION = 50
MAX_CHUNKS_PER_SOURCE    = 100
MAX_SOURCES_PER_SESSION  = 10